eureka:
 instance:
  hostname: localhost
  instance-id: ${eureka.instance.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
 client:
  service-url:
   default-zone: http://localhost:8761
   
management:
 info:
  env:
   enabled: true
 endpoints:
  web:
   exposure:
    include: health,info  
info:
 application:
  name: ${spring.application.name}
  description: This application validates the existence of a movie using omdb and returns
server:
 port: ${PORT:${SERVER_PORT:0}}

spring:
 application:
  name: verify-movie

url: http://www.omdbapi.com/
apiKey: '4e026173'